name: Build and public SDK
on:
  push:
    branches:
      - nupkg
  pull_request:
    branches:
      - nupkg
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Install NuGet
        run: |
          $sourceNugetExe = "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe"
          $targetNugetExe = "nuget.exe"
          Invoke-WebRequest $sourceNugetExe -OutFile $targetNugetExe
      - name: Restore Projects
        run: |
          .\nuget restore "$Env:GITHUB_WORKSPACE"
      - name: Build SDK
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe "$Env:GITHUB_WORKSPACE\Native.Sdk" /t:Build /p:Configuration=Release /p:Platform="x86"
      - name: Add private GitHub registry to NuGet
        run: |
          .\nuget sources add -name github -Source https://nuget.pkg.github.com/Jie2GG/index.json -Username Jie2GG -Password ${{ secrets.Nuget }}
      - name: Push generated package to GitHub registry
        run: |
          .\nuget push "$Env:GITHUB_WORKSPACE\Native.Sdk\bin\x86\release\*.nupkg" -Source github -SkipDuplicate
      - name: Push generated package to NuGet registry
        run: |
          .\nuget push "$Env:GITHUB_WORKSPACE\Native.Sdk\bin\x86\release\*.nupkg" -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.Nuget_Api }} -NoSymbols 
