name: Build and public SDK
on:
  push:
    branches:
      - nupkg
  pull_request:
    branches:
      - nupkg
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Native.Sdk/Native.Sdk.csproj
          NUGET_KEY: ${{secrets.Nuget_Api}}
          TAG_COMMIT: false
          INCLUDE_SYMBOLS: false
